const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const multer = require('multer'); // Handles files
const path = require('path');
const fs = require('fs');
require('dotenv').config();

const User = require('./models/User');
const Paper = require('./models/Paper'); // Import the new model

const app = express();
app.use(cors());
app.use(express.json());

// --- 1. SETUP FILE STORAGE ---
// Create 'uploads' folder if it doesn't exist
const uploadDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadDir)) {
  fs.mkdirSync(uploadDir);
}

// Tell Multer where to save files
const storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, 'uploads/'); 
  },
  filename: function (req, file, cb) {
    // Save as "timestamp-filename.pdf" to avoid duplicates
    cb(null, Date.now() + '-' + file.originalname);
  }
});

const upload = multer({ storage: storage });

// Allow frontend to view the files (e.g. localhost:3001/uploads/mypaper.pdf)
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

// --- DATABASE CONNECTION ---
const MONGO_URI = "mongodb+srv://admin:admin123@publazer.arhmawq.mongodb.net/?appName=Publazer";

mongoose.connect(MONGO_URI)
  .then(() => console.log("✅ DB Connected"))
  .catch(err => console.error("❌ DB Error:", err));

app.get('/', (req, res) => {
  res.send('Backend is running!');
});

// --- ROUTES ---

// 1. REGISTER
app.post('/api/register', async (req, res) => {
  try {
    const { name, email, password, department } = req.body; 
    const existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ error: "Email already in use" });

    const newUser = new User({ name, email, password, department });
    await newUser.save();
    res.status(201).json({ message: "User registered successfully!" });
  } catch (error) {
    res.status(500).json({ error: "Error registering user" });
  }
});

// 2. LOGIN
app.post('/api/login', async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email });
    if (!user) return res.status(400).json({ error: "User not found" });
    if (user.password !== password) return res.status(400).json({ error: "Invalid password" });

    res.json({
      message: "Login successful",
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        role: user.role,
        department: user.department
      }
    });
  } catch (error) {
    res.status(500).json({ error: "Error logging in" });
  }
});

// 3. UPLOAD PAPER (The Missing Piece!)
app.post('/api/papers/upload', upload.single("file"), async (req, res) => {
  try {
    const { title, abstract, keywords, author, authorId, department } = req.body;
    
    if (!req.file) {
      return res.status(400).json({ error: "No PDF file uploaded" });
    }

    const newPaper = new Paper({
      title,
      abstract,
      keywords,
      fileName: req.file.filename, // Save the filename generated by Multer
      author,
      authorId,
      department,
      plagiarismScore: Math.floor(Math.random() * 30) + 5
    });

    await newPaper.save(); // Save to MongoDB

    res.status(201).json({ message: "File uploaded successfully!", paper: newPaper });
  } catch (error) {
    console.error("Upload Error:", error);
    res.status(500).json({ error: "Failed to upload" });
  }
});

// 4. GET PAPERS ROUTE (Enhanced for Search & Filter)
app.get('/api/papers', async (req, res) => {
  try {
    const { authorId, status, search } = req.query;
    
    let query = {};

    // Filter by Author (for My Submissions)
    if (authorId) {
      query.authorId = authorId;
    }

    // Filter by Status (for Repository view)
    if (status) {
      query.status = status;
    }

    // Search by Title or Keywords (Case insensitive)
    if (search) {
      query.$or = [
        { title: { $regex: search, $options: 'i' } },
        { keywords: { $regex: search, $options: 'i' } }
      ];
    }

    const papers = await Paper.find(query).sort({ uploadDate: -1 });
    res.json(papers);
  } catch (error) {
    console.error("Fetch Error:", error);
    res.status(500).json({ error: "Failed to fetch papers" });
  }
});

// 5. DELETE PAPER ROUTE
app.delete('/api/papers/:id', async (req, res) => {
  try {
    const paper = await Paper.findById(req.params.id);
    if (!paper) return res.status(404).json({ error: "Paper not found" });

    // 1. Delete the actual file from the 'uploads' folder
    const filePath = path.join(__dirname, 'uploads', paper.fileName);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }

    // 2. Delete the record from MongoDB
    await Paper.findByIdAndDelete(req.params.id);
    
    res.json({ message: "Paper deleted successfully" });
  } catch (error) {
    console.error("Delete Error:", error);
    res.status(500).json({ error: "Error deleting paper" });
  }
});

// 6. UPDATE PAPER ROUTE (Enhanced to allow Status updates)
app.put('/api/papers/:id', async (req, res) => {
  try {
    // Now accepting 'status' as well
    const { title, abstract, keywords, status } = req.body;
    
    // Create an object with only the fields that were actually sent
    const updateData = {};
    if (title) updateData.title = title;
    if (abstract) updateData.abstract = abstract;
    if (keywords) updateData.keywords = keywords;
    if (status) updateData.status = status; // <--- This allows approval!

    const updatedPaper = await Paper.findByIdAndUpdate(
      req.params.id,
      updateData,
      { new: true }
    );
    
    res.json(updatedPaper);
  } catch (error) {
    console.error("Update Error:", error);
    res.status(500).json({ error: "Error updating paper" });
  }
});


app.listen(3001, () => {
  console.log('🚀 Server is running on port 3001');
});